// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"time"
)

// SpanApiResponse defines model for SpanApiResponse.
type SpanApiResponse struct {
	Children []SpanDTO `json:"children"`
}

// SpanDTO defines model for SpanDTO.
type SpanDTO struct {
	Children []SpanDTO `json:"children"`

	// Duration Duration in nanoseconds
	Duration  int64     `json:"duration"`
	EndTime   time.Time `json:"endTime"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	StartTime time.Time `json:"startTime"`
}
